Repository event-driven-io/emmett, pull requests merged in 2024-03, with the labels that each got.

#30 Fix martendb.io link in README.md
  README.md
Labels: bug, documentation

#24 Basic fastify package
  .DS_Store
  .gitignore
  .idea/workspace.xml
  package-lock.json
  package.json
  packages/emmett-fastify/package.json
  packages/emmett-fastify/src/e2e/decider/api.ts
  packages/emmett-fastify/src/e2e/decider/applicationLogicWithOC.int.spec.ts
  packages/emmett-fastify/src/e2e/decider/businessLogic.ts
  packages/emmett-fastify/src/e2e/decider/shoppingCart.ts
  packages/emmett-fastify/src/e2e/testing.ts
  packages/emmett-fastify/src/index.ts
  packages/emmett-fastify/tsconfig.build.json
  packages/emmett-fastify/tsconfig.json
  packages/emmett-fastify/tsup.config.ts
  tsconfig.json
Labels: enhancement, WebApi, Fastify

#33 fix(emmet-esdb): fix test case to expect correct value
  packages/emmett-esdb/src/eventStore/eventstoreDBEventStore.e2e.spec.ts
  packages/emmett/src/eventStore/inMemoryEventStore.unit.spec.ts
Labels: bug, testing

#41 Updated missing changes to tsup config
  package-lock.json
  package.json
  packages/emmett-esdb/package.json
  packages/emmett-esdb/tsup.config.ts
  packages/emmett-expressjs/package.json
  packages/emmett-expressjs/tsup.config.ts
  packages/emmett-fastify/package.json
  packages/emmett-fastify/tsup.config.ts
  packages/emmett-testcontainers/package.json
  packages/emmett-testcontainers/tsup.config.ts
  packages/emmett/package.json
  tsup.config.ts
Labels: bug, CI, compatibility

#44 Added missing @express/types peer dependency in Express.js package
  package-lock.json
  packages/emmett-expressjs/package.json
Labels: bug, dependencies

#45 Made conventional error matching in `problemDetailsMiddleware` to be based on `errorCode` property
  packages/emmett-expressjs/src/middlewares/problemDetailsMiddleware.ts
Labels: bug, WebApi, core, expressjs

#49 Bumped to 0.5.5
  src/package-lock.json
  src/package.json
  src/packages/emmett-esdb/package.json
  src/packages/emmett-expressjs/package.json
  src/packages/emmett-fastify/package.json
  src/packages/emmett-testcontainers/package.json
  src/packages/emmett/package.json
Labels: CI

#50 Fixed WebApi with Express.js and EventStoreDB by bumping to 0.5.5
  samples/webApi/expressjs-with-esdb/package-lock.json
  samples/webApi/expressjs-with-esdb/package.json
Labels: bug, WebApi, EventStoreDB, expressjs, sample

#54 Bumped to 0.6.0
  src/package-lock.json
  src/package.json
  src/packages/emmett-esdb/package.json
  src/packages/emmett-expressjs/package.json
  src/packages/emmett-fastify/package.json
  src/packages/emmett-testcontainers/package.json
  src/packages/emmett/package.json
Labels: enhancement, dependencies
